---
version: "3"

services:
  udpmask:
    image: ghcr.io/mehdisadeghidev/udpmask:latest
    restart: unless-stopped
    ports:
      - 443:443/udp
    command: -m client -p 443  -c [udpmask-server-host] -o [udpmask-server-port]
